server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${jizou.datasource.driver-class-name}
      url: jdbc:mysql://${jizou.datasource.host}:${jizou.datasource.port}/${jizou.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${jizou.datasource.username}
      password: ${jizou.datasource.password}
  redis:
    host: ${jizou.redis.host}
    port: ${jizou.redis.port}
    database: ${jizou.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jizou.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      jizou:
        mapper: debug
        service: info
        controller: info

jizou:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${jizou.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${jizou.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${jizou.jwt.admin-token-name}
    user-secret-key: ${jizou.jwt.user-secret-key}
    user-ttl: ${jizou.jwt.user-ttl}
    user-token-name: ${jizou.jwt.user-token-name}

  smms:
    url: ${jizou.smms.url}
    token: ${jizou.smms.token}

  wechat:
    appid: ${jizou.wechat.appid}
    secret: ${jizou.wechat.secret}
  shop:
    address: ${jizou.shop.address}
  baidu:
    ak: ${jizou.baidu.ak}
    latlng-url: ${jizou.baidu.latlng-url}
    routing-url: ${jizou.baidu.routing-url}
