jizou:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: gakki.00

  jwt:
    admin-secret-key: tenn
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: ji
    user-ttl: 7200000
    user-token-name: authentication

  redis:
      host: localhost
      port: 6379
      database: 5

  smms:
    url: https://smms.app/api/v2/upload
    token: 7Mmik3nEX20klXdBaLmAkNKbl8E51S3P

  wechat:
    appid: wxe47edce1249fd0f6
    secret: 84fd7a6d8fb52664f9b4562205bb028a

  shop:
    address: 湖北省武汉市洪山区珞喻路与关山大道交叉口东南侧

  baidu:
    ak: 1CU2r5sxeSpnzAqtyCV9A2294i1e2Yi0
    latlng-url: https://api.map.baidu.com/geocoding/v3
    routing-url: https://api.map.baidu.com/directionlite/v1/driving