jizou:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: gakki.00
  alioss:
    access-key-id:  ''
    access-key-secret:  ''
    bucket-name:  ''
    endpoint: ''
  redis:
      host: localhost
      port: 6379
      database: 5
  smms:
    url: https://smms.app/api/v2/upload
    token: 7Mmik3nEX20klXdBaLmAkNKbl8E51S3P

  wechat:
    appid: wxe47edce1249fd0f6
    secret: 84fd7a6d8fb52664f9b4562205bb028a